package main

type Emoji struct {
  code string
  desc string
  keywords string
}

var emojis = []*Emoji{
  {"U+1F600", "grinning face", "face, grin, grinning face"},
  {"U+1F601", "beaming face with smiling eyes", "eye, face, grin, smile, beaming face with smiling eyes"},
  {"U+1F602", "face with tears of joy", "face, joy, laugh, tear, face with tears of joy"},
  {"U+1F923", "rolling on the floor laughing", "face, floor, laugh, rolling, rolling on the floor laughing"},
  {"U+1F603", "grinning face with big eyes", "face, mouth, open, smile, grinning face with big eyes"},
  {"U+1F604", "grinning face with smiling eyes", "eye, face, mouth, open, smile, grinning face with smiling eyes"},
  {"U+1F605", "grinning face with sweat", "cold, face, open, smile, sweat, grinning face with sweat"},
  {"U+1F606", "grinning squinting face", "face, laugh, mouth, open, satisfied, smile, grinning squinting face"},
  {"U+1F609", "winking face", "face, wink, winking face"},
  {"U+1F60A", "smiling face with smiling eyes", "blush, eye, face, smile, smiling face with smiling eyes"},
  {"U+1F60B", "face savoring food", "delicious, face, savouring, smile, um, yum, face savoring food"},
  {"U+1F60E", "smiling face with sunglasses", "bright, cool, eye, eyewear, face, glasses, smile, sun, sunglasses, smiling face with sunglasses"},
  {"U+1F60D", "smiling face with heart-eyes", "eye, face, love, smile, smiling face with heart-eyes"},
  {"U+1F618", "face blowing a kiss", "face, kiss, face blowing a kiss"},
  {"U+1F617", "kissing face", "face, kiss, kissing face"},
  {"U+1F619", "kissing face with smiling eyes", "eye, face, kiss, smile, kissing face with smiling eyes"},
  {"U+1F61A", "kissing face with closed eyes", "closed, eye, face, kiss, kissing face with closed eyes"},
  {"U+263A", "smiling face", "face, outlined, relaxed, smile, smiling face"},
  {"U+1F642", "slightly smiling face", "face, smile, slightly smiling face"},
  {"U+1F917", "hugging face", "face, hug, hugging, hugging face"},
  {"U+1F929", "⊛ star-struck", "eyes, face, grinning, star, starry-eyed, ⊛ star-struck"},
  {"U+1F914", "thinking face", "face, thinking, thinking face"},
  {"U+1F928", "⊛ face with raised eyebrow", "distrust, skeptic, disapproval, disbelief, mild surprise, scepticism, ⊛ face with raised eyebrow"},
  {"U+1F610", "neutral face", "deadpan, face, neutral, neutral face"},
  {"U+1F611", "expressionless face", "expressionless, face, inexpressive, unexpressive, expressionless face"},
  {"U+1F636", "face without mouth", "face, mouth, quiet, silent, face without mouth"},
  {"U+1F644", "face with rolling eyes", "eyes, face, rolling, face with rolling eyes"},
  {"U+1F60F", "smirking face", "face, smirk, smirking face"},
  {"U+1F623", "persevering face", "face, persevere, persevering face"},
  {"U+1F625", "sad but relieved face", "disappointed, face, relieved, whew, sad but relieved face"},
  {"U+1F62E", "face with open mouth", "face, mouth, open, sympathy, face with open mouth"},
  {"U+1F910", "zipper-mouth face", "face, mouth, zipper, zipper-mouth face"},
  {"U+1F62F", "hushed face", "face, hushed, stunned, surprised, hushed face"},
  {"U+1F62A", "sleepy face", "face, sleep, sleepy face"},
  {"U+1F62B", "tired face", "face, tired, tired face"},
  {"U+1F634", "sleeping face", "face, sleep, zzz, sleeping face"},
  {"U+1F60C", "relieved face", "face, relieved, relieved face"},
  {"U+1F61B", "face with tongue", "face, tongue, face with tongue"},
  {"U+1F61C", "winking face with tongue", "eye, face, joke, tongue, wink, winking face with tongue"},
  {"U+1F61D", "squinting face with tongue", "eye, face, horrible, taste, tongue, squinting face with tongue"},
  {"U+1F924", "drooling face", "drooling, face, drooling face"},
  {"U+1F612", "unamused face", "face, unamused, unhappy, unamused face"},
  {"U+1F613", "downcast face with sweat", "cold, face, sweat, downcast face with sweat"},
  {"U+1F614", "pensive face", "dejected, face, pensive, pensive face"},
  {"U+1F615", "confused face", "confused, face, confused face"},
  {"U+1F643", "upside-down face", "face, upside-down, upside-down face"},
  {"U+1F911", "money-mouth face", "face, money, mouth, money-mouth face"},
  {"U+1F632", "astonished face", "astonished, face, shocked, totally, astonished face"},
  {"U+2639", "frowning face", "face, frown, frowning face"},
  {"U+1F641", "slightly frowning face", "face, frown, slightly frowning face"},
  {"U+1F616", "confounded face", "confounded, face, confounded face"},
  {"U+1F61E", "disappointed face", "disappointed, face, disappointed face"},
  {"U+1F61F", "worried face", "face, worried, worried face"},
  {"U+1F624", "face with steam from nose", "face, triumph, won, face with steam from nose"},
  {"U+1F622", "crying face", "cry, face, sad, tear, crying face"},
  {"U+1F62D", "loudly crying face", "cry, face, sad, sob, tear, loudly crying face"},
  {"U+1F626", "frowning face with open mouth", "face, frown, mouth, open, frowning face with open mouth"},
  {"U+1F627", "anguished face", "anguished, face, anguished face"},
  {"U+1F628", "fearful face", "face, fear, fearful, scared, fearful face"},
  {"U+1F629", "weary face", "face, tired, weary, weary face"},
  {"U+1F92F", "⊛ exploding head", "shocked, ⊛ exploding head"},
  {"U+1F62C", "grimacing face", "face, grimace, grimacing face"},
  {"U+1F630", "anxious face with sweat", "blue, cold, face, mouth, open, rushed, sweat, anxious face with sweat"},
  {"U+1F631", "face screaming in fear", "face, fear, fearful, munch, scared, scream, face screaming in fear"},
  {"U+1F633", "flushed face", "dazed, face, flushed, flushed face"},
  {"U+1F92A", "⊛ crazy face", "eye, large, small, ⊛ crazy face"},
  {"U+1F635", "dizzy face", "dizzy, face, dizzy face"},
  {"U+1F621", "pouting face", "angry, face, mad, pouting, rage, red, pouting face"},
  {"U+1F620", "angry face", "angry, face, mad, angry face"},
  {"U+1F92C", "⊛ face with symbols on mouth", "swearing, cursing, ⊛ face with symbols on mouth"},
  {"U+1F637", "face with medical mask", "cold, doctor, face, mask, medicine, sick, face with medical mask"},
  {"U+1F912", "face with thermometer", "face, ill, sick, thermometer, face with thermometer"},
  {"U+1F915", "face with head-bandage", "bandage, face, hurt, injury, face with head-bandage"},
  {"U+1F922", "nauseated face", "face, nauseated, vomit, nauseated face"},
  {"U+1F92E", "⊛ face vomiting", "sick, vomit, ⊛ face vomiting"},
  {"U+1F927", "sneezing face", "face, gesundheit, sneeze, sneezing face"},
  {"U+1F607", "smiling face with halo", "angel, face, fairy tale, fantasy, halo, innocent, smile, smiling face with halo"},
  {"U+1F920", "cowboy hat face", "cowboy, cowgirl, face, hat, cowboy hat face"},
  {"U+1F921", "clown face", "clown, face, clown face"},
  {"U+1F925", "lying face", "face, lie, pinocchio, lying face"},
  {"U+1F92B", "⊛ shushing face", "quiet, shush, ⊛ shushing face"},
  {"U+1F92D", "⊛ face with hand over mouth", "whoops, shock, sudden realization, surprise, ⊛ face with hand over mouth"},
  {"U+1F9D0", "⊛ face with monocle", "stuffy, wealthy, ⊛ face with monocle"},
  {"U+1F913", "nerd face", "face, geek, nerd, nerd face"},
  {"U+1F608", "smiling face with horns", "face, fairy tale, fantasy, horns, smile, smiling face with horns"},
  {"U+1F47F", "angry face with horns", "demon, devil, face, fairy tale, fantasy, imp, angry face with horns"},
  {"U+1F479", "ogre", "creature, face, fairy tale, fantasy, monster, troll, ogre"},
  {"U+1F47A", "goblin", "creature, face, fairy tale, fantasy, monster, goblin"},
  {"U+1F480", "skull", "death, face, fairy tale, monster, skull"},
  {"U+2620", "skull and crossbones", "crossbones, death, face, monster, skull, skull and crossbones"},
  {"U+1F47B", "ghost", "creature, face, fairy tale, fantasy, monster, ghost"},
  {"U+1F47D", "alien", "creature, extraterrestrial, face, fairy tale, fantasy, monster, ufo, alien"},
  {"U+1F47E", "alien monster", "alien, creature, extraterrestrial, face, fairy tale, fantasy, monster, ufo, alien monster"},
  {"U+1F916", "robot face", "face, monster, robot, robot face"},
  {"U+1F4A9", "pile of poo", "comic, dung, face, monster, poo, poop, pile of poo"},
  {"U+1F63A", "grinning cat face", "cat, face, mouth, open, smile, grinning cat face"},
  {"U+1F638", "grinning cat face with smiling eyes", "cat, eye, face, grin, smile, grinning cat face with smiling eyes"},
  {"U+1F639", "cat face with tears of joy", "cat, face, joy, tear, cat face with tears of joy"},
  {"U+1F63B", "smiling cat face with heart-eyes", "cat, eye, face, love, smile, smiling cat face with heart-eyes"},
  {"U+1F63C", "cat face with wry smile", "cat, face, ironic, smile, wry, cat face with wry smile"},
  {"U+1F63D", "kissing cat face", "cat, eye, face, kiss, kissing cat face"},
  {"U+1F640", "weary cat face", "cat, face, oh, surprised, weary, weary cat face"},
  {"U+1F63F", "crying cat face", "cat, cry, face, sad, tear, crying cat face"},
  {"U+1F63E", "pouting cat face", "cat, face, pouting, pouting cat face"},
  {"U+1F648", "see-no-evil monkey", "evil, face, forbidden, gesture, monkey, no, not, prohibited, see, see-no-evil monkey"},
  {"U+1F649", "hear-no-evil monkey", "evil, face, forbidden, gesture, hear, monkey, no, not, prohibited, hear-no-evil monkey"},
  {"U+1F64A", "speak-no-evil monkey", "evil, face, forbidden, gesture, monkey, no, not, prohibited, speak, speak-no-evil monkey"},
  {"U+1F476", "baby", "baby, young, baby"},
  {"U+1F9D2", "⊛ child", "gender-neutral, young, (no specific gender), ⊛ child"},
  {"U+1F466", "boy", "boy, young, boy"},
  {"U+1F467", "girl", "Virgo, young, zodiac, girl"},
  {"U+1F9D1", "⊛ adult", "gender-neutral, (no specific gender), ⊛ adult"},
  {"U+1F468", "man", "man, man"},
  {"U+1F469", "woman", "woman, woman"},
  {"U+1F9D3", "⊛ older adult", "gender-neutral, old, (no specific gender), ⊛ older adult"},
  {"U+1F474", "old man", "man, old, old man"},
  {"U+1F475", "old woman", "old, woman, old woman"},
  {"U+1F46E", "police officer", "cop, officer, police, police officer"},
  {"U+1F575", "detective", "detective, sleuth, spy, detective"},
  {"U+1F482", "guard", "guard, guard"},
  {"U+1F477", "construction worker", "construction, hat, worker, construction worker"},
  {"U+1F934", "prince", "prince, prince"},
  {"U+1F478", "princess", "fairy tale, fantasy, princess"},
  {"U+1F473", "person wearing turban", "turban, person wearing turban"},
  {"U+1F472", "man with Chinese cap", "gua pi mao, hat, man, man with Chinese cap"},
  {"U+1F9D5", "⊛ woman with headscarf", "headscarf, hijab, mantilla, tichel, bandana, head kerchief, ⊛ woman with headscarf"},
  {"U+1F9D4", "⊛ bearded person", "beard, bewhiskered, ⊛ bearded person"},
  {"U+1F471", "blond-haired person", "blond, blond-haired person"},
  {"U+1F935", "man in tuxedo", "groom, man, tuxedo, man in tuxedo"},
  {"U+1F470", "bride with veil", "bride, veil, wedding, bride with veil"},
  {"U+1F930", "pregnant woman", "pregnant, woman, pregnant woman"},
  {"U+1F931", "⊛ breast-feeding", "baby, breast, nursing, ⊛ breast-feeding"},
  {"U+1F47C", "baby angel", "angel, baby, face, fairy tale, fantasy, baby angel"},
  {"U+1F385", "Santa Claus", "celebration, Christmas, claus, father, santa, Santa Claus"},
  {"U+1F936", "Mrs. Claus", "celebration, Christmas, claus, mother, Mrs., Mrs. Claus"},
  {"U+1F9D9", "⊛ mage", "sorcerer, sorceress, witch, wizard, ⊛ mage"},
  {"U+1F9DA", "⊛ fairy", "Oberon, Puck, Titania, ⊛ fairy"},
  {"U+1F9DB", "⊛ vampire", "Dracula, undead, ⊛ vampire"},
  {"U+1F9DC", "⊛ merperson", "mermaid, merman, merwoman, ⊛ merperson"},
  {"U+1F9DD", "⊛ elf", "magical, LOTR style, ⊛ elf"},
  {"U+1F9DE", "⊛ genie", "djinn, (non-human color), ⊛ genie"},
  {"U+1F9DF", "⊛ zombie", "undead, walking dead, (non-human color), ⊛ zombie"},
  {"U+1F64D", "person frowning", "frown, gesture, person frowning"},
  {"U+1F64E", "person pouting", "gesture, pouting, person pouting"},
  {"U+1F645", "person gesturing NO", "forbidden, gesture, hand, no, not, prohibited, person gesturing NO"},
  {"U+1F646", "person gesturing OK", "gesture, hand, OK, person gesturing OK"},
  {"U+1F481", "person tipping hand", "hand, help, information, sassy, tipping, person tipping hand"},
  {"U+1F64B", "person raising hand", "gesture, hand, happy, raised, person raising hand"},
  {"U+1F647", "person bowing", "apology, bow, gesture, sorry, person bowing"},
  {"U+1F926", "person facepalming", "disbelief, exasperation, face, palm, person facepalming"},
  {"U+1F937", "person shrugging", "doubt, ignorance, indifference, shrug, person shrugging"},
  {"U+1F486", "person getting massage", "face, massage, salon, person getting massage"},
  {"U+1F487", "person getting haircut", "barber, beauty, haircut, parlor, person getting haircut"},
  {"U+1F6B6", "person walking", "hike, walk, walking, person walking"},
  {"U+1F3C3", "person running", "marathon, running, person running"},
  {"U+1F483", "woman dancing", "dancing, woman, woman dancing"},
  {"U+1F57A", "man dancing", "dance, man, man dancing"},
  {"U+1F46F", "people with bunny ears", "bunny ear, dancer, partying, people with bunny ears"},
  {"U+1F9D6", "⊛ person in steamy room", "sauna, steam room, hamam, steambath, ⊛ person in steamy room"},
  {"U+1F9D7", "⊛ person climbing", "climber, ⊛ person climbing"},
  {"U+1F9D8", "⊛ person in lotus position", "meditation, yoga, serenity, ⊛ person in lotus position"},
  {"U+1F6C0", "person taking bath", "bath, bathtub, person taking bath"},
  {"U+1F6CC", "person in bed", "hotel, sleep, person in bed"},
  {"U+1F574", "man in suit levitating", "business, man, suit, man in suit levitating"},
  {"U+1F5E3", "speaking head", "face, head, silhouette, speak, speaking, speaking head"},
  {"U+1F464", "bust in silhouette", "bust, silhouette, bust in silhouette"},
  {"U+1F465", "busts in silhouette", "bust, silhouette, busts in silhouette"},
  {"U+1F93A", "person fencing", "fencer, fencing, sword, person fencing"},
  {"U+1F3C7", "horse racing", "horse, jockey, racehorse, racing, horse racing"},
  {"U+26F7", "skier", "ski, snow, skier"},
  {"U+1F3C2", "snowboarder", "ski, snow, snowboard, snowboarder"},
  {"U+1F3CC", "person golfing", "ball, golf, person golfing"},
  {"U+1F3C4", "person surfing", "surfing, person surfing"},
  {"U+1F6A3", "person rowing boat", "boat, rowboat, person rowing boat"},
  {"U+1F3CA", "person swimming", "swim, person swimming"},
  {"U+26F9", "person bouncing ball", "ball, person bouncing ball"},
  {"U+1F3CB", "person lifting weights", "lifter, weight, person lifting weights"},
  {"U+1F6B4", "person biking", "bicycle, biking, cyclist, person biking"},
  {"U+1F6B5", "person mountain biking", "bicycle, bicyclist, bike, cyclist, mountain, person mountain biking"},
  {"U+1F3CE", "racing car", "car, racing, racing car"},
  {"U+1F3CD", "motorcycle", "racing, motorcycle"},
  {"U+1F938", "person cartwheeling", "cartwheel, gymnastics, person cartwheeling"},
  {"U+1F93C", "people wrestling", "wrestle, wrestler, people wrestling"},
  {"U+1F93D", "person playing water polo", "polo, water, person playing water polo"},
  {"U+1F93E", "person playing handball", "ball, handball, person playing handball"},
  {"U+1F939", "person juggling", "balance, juggle, multitask, skill, person juggling"},
  {"U+1F46B", "man and woman holding hands", "couple, hand, hold, man, woman, man and woman holding hands"},
  {"U+1F46C", "two men holding hands", "couple, Gemini, hand, hold, man, twins, zodiac, two men holding hands"},
  {"U+1F46D", "two women holding hands", "couple, hand, hold, woman, two women holding hands"},
  {"U+1F48F", "kiss", "couple, kiss"},
  {"U+1F491", "couple with heart", "couple, love, couple with heart"},
  {"U+1F46A", "family", "family, family"},
  {"U+1F933", "selfie", "camera, phone, selfie, selfie"},
  {"U+1F4AA", "flexed biceps", "biceps, comic, flex, muscle, flexed biceps"},
  {"U+1F448", "backhand index pointing left", "backhand, finger, hand, index, point, backhand index pointing left"},
  {"U+1F449", "backhand index pointing right", "backhand, finger, hand, index, point, backhand index pointing right"},
  {"U+261D", "index pointing up", "finger, hand, index, point, up, index pointing up"},
  {"U+1F446", "backhand index pointing up", "backhand, finger, hand, index, point, up, backhand index pointing up"},
  {"U+1F595", "middle finger", "finger, hand, middle finger"},
  {"U+1F447", "backhand index pointing down", "backhand, down, finger, hand, index, point, backhand index pointing down"},
  {"U+270C", "victory hand", "hand, v, victory, victory hand"},
  {"U+1F91E", "crossed fingers", "cross, finger, hand, luck, crossed fingers"},
  {"U+1F596", "vulcan salute", "finger, hand, spock, vulcan, vulcan salute"},
  {"U+1F918", "sign of the horns", "finger, hand, horns, rock-on, sign of the horns"},
  {"U+1F919", "call me hand", "call, hand, call me hand"},
  {"U+1F590", "hand with fingers splayed", "finger, hand, splayed, hand with fingers splayed"},
  {"U+270B", "raised hand", "hand, raised hand"},
  {"U+1F44C", "OK hand", "hand, OK, OK hand"},
  {"U+1F44D", "thumbs up", "+1, hand, thumb, up, thumbs up"},
  {"U+1F44E", "thumbs down", "-1, down, hand, thumb, thumbs down"},
  {"U+270A", "raised fist", "clenched, fist, hand, punch, raised fist"},
  {"U+1F44A", "oncoming fist", "clenched, fist, hand, punch, oncoming fist"},
  {"U+1F91B", "left-facing fist", "fist, leftwards, left-facing fist"},
  {"U+1F91C", "right-facing fist", "fist, rightwards, right-facing fist"},
  {"U+1F91A", "raised back of hand", "backhand, raised, raised back of hand"},
  {"U+1F44B", "waving hand", "hand, wave, waving, waving hand"},
  {"U+1F91F", "⊛ love-you gesture", "hand, ILY, ⊛ love-you gesture"},
  {"U+270D", "writing hand", "hand, write, writing hand"},
  {"U+1F44F", "clapping hands", "clap, hand, clapping hands"},
  {"U+1F450", "open hands", "hand, open, open hands"},
  {"U+1F64C", "raising hands", "celebration, gesture, hand, hooray, raised, raising hands"},
  {"U+1F932", "⊛ palms up together", "prayer, cupped hands, ⊛ palms up together"},
  {"U+1F64F", "folded hands", "ask, bow, folded, gesture, hand, please, pray, thanks, folded hands"},
  {"U+1F91D", "handshake", "agreement, hand, handshake, meeting, shake, handshake"},
  {"U+1F485", "nail polish", "care, cosmetics, manicure, nail, polish, nail polish"},
  {"U+1F442", "ear", "body, ear"},
  {"U+1F443", "nose", "body, nose"},
  {"U+1F463", "footprints", "clothing, footprint, print, footprints"},
  {"U+1F440", "eyes", "eye, face, eyes"},
  {"U+1F441", "eye", "body, eye"},
  {"U+1F9E0", "⊛ brain", "intelligent, ⊛ brain"},
  {"U+1F445", "tongue", "body, tongue"},
  {"U+1F444", "mouth", "lips, mouth"},
  {"U+1F48B", "kiss mark", "kiss, lips, kiss mark"},
  {"U+1F498", "heart with arrow", "arrow, cupid, heart with arrow"},
  {"U+2764", "red heart", "heart, red heart"},
  {"U+1F493", "beating heart", "beating, heartbeat, pulsating, beating heart"},
  {"U+1F494", "broken heart", "break, broken, broken heart"},
  {"U+1F495", "two hearts", "love, two hearts"},
  {"U+1F496", "sparkling heart", "excited, sparkle, sparkling heart"},
  {"U+1F497", "growing heart", "excited, growing, nervous, pulse, growing heart"},
  {"U+1F499", "blue heart", "blue, blue heart"},
  {"U+1F49A", "green heart", "green, green heart"},
  {"U+1F49B", "yellow heart", "yellow, yellow heart"},
  {"U+1F9E1", "⊛ orange heart", "orange, ⊛ orange heart"},
  {"U+1F49C", "purple heart", "purple, purple heart"},
  {"U+1F5A4", "black heart", "black, evil, wicked, black heart"},
  {"U+1F49D", "heart with ribbon", "ribbon, valentine, heart with ribbon"},
  {"U+1F49E", "revolving hearts", "revolving, revolving hearts"},
  {"U+1F49F", "heart decoration", "heart, heart decoration"},
  {"U+2763", "heavy heart exclamation", "exclamation, mark, punctuation, heavy heart exclamation"},
  {"U+1F48C", "love letter", "heart, letter, love, mail, love letter"},
  {"U+1F4A4", "zzz", "comic, sleep, zzz"},
  {"U+1F4A2", "anger symbol", "angry, comic, mad, anger symbol"},
  {"U+1F4A3", "bomb", "comic, bomb"},
  {"U+1F4A5", "collision", "boom, comic, collision"},
  {"U+1F4A6", "sweat droplets", "comic, splashing, sweat, sweat droplets"},
  {"U+1F4A8", "dashing away", "comic, dash, running, dashing away"},
  {"U+1F4AB", "dizzy", "comic, star, dizzy"},
  {"U+1F4AC", "speech balloon", "balloon, bubble, comic, dialog, speech, speech balloon"},
  {"U+1F5E8", "left speech bubble", "dialog, speech, left speech bubble"},
  {"U+1F5EF", "right anger bubble", "angry, balloon, bubble, mad, right anger bubble"},
  {"U+1F4AD", "thought balloon", "balloon, bubble, comic, thought, thought balloon"},
  {"U+1F573", "hole", "hole, hole"},
  {"U+1F453", "glasses", "clothing, eye, eyeglasses, eyewear, glasses"},
  {"U+1F576", "sunglasses", "dark, eye, eyewear, glasses, sunglasses"},
  {"U+1F454", "necktie", "clothing, necktie"},
  {"U+1F455", "t-shirt", "clothing, shirt, tshirt, t-shirt"},
  {"U+1F456", "jeans", "clothing, pants, trousers, jeans"},
  {"U+1F9E3", "⊛ scarf", "neck, ⊛ scarf"},
  {"U+1F9E4", "⊛ gloves", "hand, ⊛ gloves"},
  {"U+1F9E5", "⊛ coat", "jacket, ⊛ coat"},
  {"U+1F9E6", "⊛ socks", "stocking, ⊛ socks"},
  {"U+1F457", "dress", "clothing, dress"},
  {"U+1F458", "kimono", "clothing, kimono"},
  {"U+1F459", "bikini", "clothing, swim, bikini"},
  {"U+1F45A", "woman’s clothes", "clothing, woman, woman’s clothes"},
  {"U+1F45B", "purse", "clothing, coin, purse"},
  {"U+1F45C", "handbag", "bag, clothing, purse, handbag"},
  {"U+1F45D", "clutch bag", "bag, clothing, pouch, clutch bag"},
  {"U+1F6CD", "shopping bags", "bag, hotel, shopping, shopping bags"},
  {"U+1F392", "school backpack", "bag, satchel, school, school backpack"},
  {"U+1F45E", "man’s shoe", "clothing, man, shoe, man’s shoe"},
  {"U+1F45F", "running shoe", "athletic, clothing, shoe, sneaker, running shoe"},
  {"U+1F460", "high-heeled shoe", "clothing, heel, shoe, woman, high-heeled shoe"},
  {"U+1F461", "woman’s sandal", "clothing, sandal, shoe, woman, woman’s sandal"},
  {"U+1F462", "woman’s boot", "boot, clothing, shoe, woman, woman’s boot"},
  {"U+1F451", "crown", "clothing, king, queen, crown"},
  {"U+1F452", "woman’s hat", "clothing, hat, woman, woman’s hat"},
  {"U+1F3A9", "top hat", "clothing, hat, top, tophat, top hat"},
  {"U+1F393", "graduation cap", "cap, celebration, clothing, graduation, hat, graduation cap"},
  {"U+1F9E2", "⊛ billed cap", "baseball cap, ⊛ billed cap"},
  {"U+26D1", "rescue worker’s helmet", "aid, cross, face, hat, helmet, rescue worker’s helmet"},
  {"U+1F4FF", "prayer beads", "beads, clothing, necklace, prayer, religion, prayer beads"},
  {"U+1F484", "lipstick", "cosmetics, makeup, lipstick"},
  {"U+1F48D", "ring", "diamond, ring"},
  {"U+1F48E", "gem stone", "diamond, gem, jewel, gem stone"},
  {"U+1F435", "monkey face", "face, monkey, monkey face"},
  {"U+1F412", "monkey", "monkey, monkey"},
  {"U+1F98D", "gorilla", "gorilla, gorilla"},
  {"U+1F436", "dog face", "dog, face, pet, dog face"},
  {"U+1F415", "dog", "pet, dog"},
  {"U+1F429", "poodle", "dog, poodle"},
  {"U+1F43A", "wolf face", "face, wolf, wolf face"},
  {"U+1F98A", "fox face", "face, fox, fox face"},
  {"U+1F431", "cat face", "cat, face, pet, cat face"},
  {"U+1F408", "cat", "pet, cat"},
  {"U+1F981", "lion face", "face, Leo, lion, zodiac, lion face"},
  {"U+1F42F", "tiger face", "face, tiger, tiger face"},
  {"U+1F405", "tiger", "tiger, tiger"},
  {"U+1F406", "leopard", "leopard, leopard"},
  {"U+1F434", "horse face", "face, horse, horse face"},
  {"U+1F40E", "horse", "equestrian, racehorse, racing, horse"},
  {"U+1F984", "unicorn face", "face, unicorn, unicorn face"},
  {"U+1F993", "⊛ zebra", "stripe, ⊛ zebra"},
  {"U+1F98C", "deer", "deer, deer"},
  {"U+1F42E", "cow face", "cow, face, cow face"},
  {"U+1F402", "ox", "bull, Taurus, zodiac, ox"},
  {"U+1F403", "water buffalo", "buffalo, water, water buffalo"},
  {"U+1F404", "cow", "cow, cow"},
  {"U+1F437", "pig face", "face, pig, pig face"},
  {"U+1F416", "pig", "sow, pig"},
  {"U+1F417", "boar", "pig, boar"},
  {"U+1F43D", "pig nose", "face, nose, pig, pig nose"},
  {"U+1F40F", "ram", "Aries, male, sheep, zodiac, ram"},
  {"U+1F411", "ewe", "female, sheep, ewe"},
  {"U+1F410", "goat", "Capricorn, zodiac, goat"},
  {"U+1F42A", "camel", "dromedary, hump, camel"},
  {"U+1F42B", "two-hump camel", "bactrian, camel, hump, two-hump camel"},
  {"U+1F992", "⊛ giraffe", "spots, ⊛ giraffe"},
  {"U+1F418", "elephant", "elephant, elephant"},
  {"U+1F98F", "rhinoceros", "rhinoceros, rhinoceros"},
  {"U+1F42D", "mouse face", "face, mouse, mouse face"},
  {"U+1F401", "mouse", "mouse, mouse"},
  {"U+1F400", "rat", "rat, rat"},
  {"U+1F439", "hamster face", "face, hamster, pet, hamster face"},
  {"U+1F430", "rabbit face", "bunny, face, pet, rabbit, rabbit face"},
  {"U+1F407", "rabbit", "bunny, pet, rabbit"},
  {"U+1F43F", "chipmunk", "chipmunk, chipmunk"},
  {"U+1F994", "⊛ hedgehog", "spiny, ⊛ hedgehog"},
  {"U+1F987", "bat", "bat, vampire, bat"},
  {"U+1F43B", "bear face", "bear, face, bear face"},
  {"U+1F428", "koala", "bear, koala"},
  {"U+1F43C", "panda face", "face, panda, panda face"},
  {"U+1F43E", "paw prints", "feet, paw, print, paw prints"},
  {"U+1F983", "turkey", "bird, turkey, turkey"},
  {"U+1F414", "chicken", "bird, chicken, chicken"},
  {"U+1F413", "rooster", "bird, rooster, rooster"},
  {"U+1F423", "hatching chick", "baby, bird, chick, hatching, hatching chick"},
  {"U+1F424", "baby chick", "baby, bird, chick, baby chick"},
  {"U+1F425", "front-facing baby chick", "baby, bird, chick, front-facing baby chick"},
  {"U+1F426", "bird", "bird, bird"},
  {"U+1F427", "penguin", "bird, penguin, penguin"},
  {"U+1F54A", "dove", "bird, fly, peace, dove"},
  {"U+1F985", "eagle", "bird, eagle, eagle"},
  {"U+1F986", "duck", "bird, duck, duck"},
  {"U+1F989", "owl", "bird, owl, wise, owl"},
  {"U+1F438", "frog face", "face, frog, frog face"},
  {"U+1F40A", "crocodile", "crocodile, crocodile"},
  {"U+1F422", "turtle", "terrapin, tortoise, turtle, turtle"},
  {"U+1F98E", "lizard", "lizard, reptile, lizard"},
  {"U+1F40D", "snake", "bearer, Ophiuchus, serpent, zodiac, snake"},
  {"U+1F432", "dragon face", "dragon, face, fairy tale, dragon face"},
  {"U+1F409", "dragon", "fairy tale, dragon"},
  {"U+1F995", "⊛ sauropod", "brachiosaurus, brontosaurus, diplodocus, ⊛ sauropod"},
  {"U+1F996", "⊛ T-Rex", "Tyrannosaurus Rex, ⊛ T-Rex"},
  {"U+1F433", "spouting whale", "face, spouting, whale, spouting whale"},
  {"U+1F40B", "whale", "whale, whale"},
  {"U+1F42C", "dolphin", "flipper, dolphin"},
  {"U+1F41F", "fish", "Pisces, zodiac, fish"},
  {"U+1F420", "tropical fish", "fish, tropical, tropical fish"},
  {"U+1F421", "blowfish", "fish, blowfish"},
  {"U+1F988", "shark", "fish, shark, shark"},
  {"U+1F419", "octopus", "octopus, octopus"},
  {"U+1F41A", "spiral shell", "shell, spiral, spiral shell"},
  {"U+1F980", "crab", "Cancer, zodiac, crab"},
  {"U+1F990", "shrimp", "food, shellfish, shrimp, small, shrimp"},
  {"U+1F991", "squid", "food, molusc, squid, squid"},
  {"U+1F40C", "snail", "snail, snail"},
  {"U+1F98B", "butterfly", "butterfly, insect, pretty, butterfly"},
  {"U+1F41B", "bug", "insect, bug"},
  {"U+1F41C", "ant", "insect, ant"},
  {"U+1F41D", "honeybee", "bee, insect, honeybee"},
  {"U+1F41E", "lady beetle", "beetle, insect, ladybird, ladybug, lady beetle"},
  {"U+1F997", "⊛ cricket", "grasshopper, Orthoptera, ⊛ cricket"},
  {"U+1F577", "spider", "insect, spider"},
  {"U+1F578", "spider web", "spider, web, spider web"},
  {"U+1F982", "scorpion", "scorpio, Scorpius, zodiac, scorpion"},
  {"U+1F490", "bouquet", "flower, bouquet"},
  {"U+1F338", "cherry blossom", "blossom, cherry, flower, cherry blossom"},
  {"U+1F4AE", "white flower", "flower, white flower"},
  {"U+1F3F5", "rosette", "plant, rosette"},
  {"U+1F339", "rose", "flower, rose"},
  {"U+1F940", "wilted flower", "flower, wilted, wilted flower"},
  {"U+1F33A", "hibiscus", "flower, hibiscus"},
  {"U+1F33B", "sunflower", "flower, sun, sunflower"},
  {"U+1F33C", "blossom", "flower, blossom"},
  {"U+1F337", "tulip", "flower, tulip"},
  {"U+1F331", "seedling", "young, seedling"},
  {"U+1F332", "evergreen tree", "tree, evergreen tree"},
  {"U+1F333", "deciduous tree", "deciduous, shedding, tree, deciduous tree"},
  {"U+1F334", "palm tree", "palm, tree, palm tree"},
  {"U+1F335", "cactus", "plant, cactus"},
  {"U+1F33E", "sheaf of rice", "ear, grain, rice, sheaf of rice"},
  {"U+1F33F", "herb", "leaf, herb"},
  {"U+2618", "shamrock", "plant, shamrock"},
  {"U+1F340", "four leaf clover", "4, clover, four, leaf, four leaf clover"},
  {"U+1F341", "maple leaf", "falling, leaf, maple, maple leaf"},
  {"U+1F342", "fallen leaf", "falling, leaf, fallen leaf"},
  {"U+1F343", "leaf fluttering in wind", "blow, flutter, leaf, wind, leaf fluttering in wind"},
  {"U+1F347", "grapes", "fruit, grape, grapes"},
  {"U+1F348", "melon", "fruit, melon"},
  {"U+1F349", "watermelon", "fruit, watermelon"},
  {"U+1F34A", "tangerine", "fruit, orange, tangerine"},
  {"U+1F34B", "lemon", "citrus, fruit, lemon"},
  {"U+1F34C", "banana", "fruit, banana"},
  {"U+1F34D", "pineapple", "fruit, pineapple"},
  {"U+1F34E", "red apple", "apple, fruit, red, red apple"},
  {"U+1F34F", "green apple", "apple, fruit, green, green apple"},
  {"U+1F350", "pear", "fruit, pear"},
  {"U+1F351", "peach", "fruit, peach"},
  {"U+1F352", "cherries", "cherry, fruit, cherries"},
  {"U+1F353", "strawberry", "berry, fruit, strawberry"},
  {"U+1F95D", "kiwi fruit", "food, fruit, kiwi, kiwi fruit"},
  {"U+1F345", "tomato", "fruit, vegetable, tomato"},
  {"U+1F965", "⊛ coconut", "palm, piña colada, ⊛ coconut"},
  {"U+1F951", "avocado", "avocado, food, fruit, avocado"},
  {"U+1F346", "eggplant", "aubergine, vegetable, eggplant"},
  {"U+1F954", "potato", "food, potato, vegetable, potato"},
  {"U+1F955", "carrot", "carrot, food, vegetable, carrot"},
  {"U+1F33D", "ear of corn", "corn, ear, maize, maze, ear of corn"},
  {"U+1F336", "hot pepper", "hot, pepper, hot pepper"},
  {"U+1F952", "cucumber", "cucumber, food, pickle, vegetable, cucumber"},
  {"U+1F966", "⊛ broccoli", "wild cabbage, ⊛ broccoli"},
  {"U+1F344", "mushroom", "toadstool, mushroom"},
  {"U+1F95C", "peanuts", "food, nut, peanut, vegetable, peanuts"},
  {"U+1F330", "chestnut", "plant, chestnut"},
  {"U+1F35E", "bread", "loaf, bread"},
  {"U+1F950", "croissant", "bread, crescent roll, croissant, food, french, croissant"},
  {"U+1F956", "baguette bread", "baguette, bread, food, french, baguette bread"},
  {"U+1F968", "⊛ pretzel", "twisted, convoluted, ⊛ pretzel"},
  {"U+1F95E", "pancakes", "crêpe, food, hotcake, pancake, pancakes"},
  {"U+1F9C0", "cheese wedge", "cheese, cheese wedge"},
  {"U+1F356", "meat on bone", "bone, meat, meat on bone"},
  {"U+1F357", "poultry leg", "bone, chicken, leg, poultry, poultry leg"},
  {"U+1F969", "⊛ cut of meat", "chop, lambchop, porkchop, steak, ⊛ cut of meat"},
  {"U+1F953", "bacon", "bacon, food, meat, bacon"},
  {"U+1F354", "hamburger", "burger, hamburger"},
  {"U+1F35F", "french fries", "french, fries, french fries"},
  {"U+1F355", "pizza", "cheese, slice, pizza"},
  {"U+1F32D", "hot dog", "frankfurter, hotdog, sausage, hot dog"},
  {"U+1F96A", "⊛ sandwich", "bread, ⊛ sandwich"},
  {"U+1F32E", "taco", "mexican, taco"},
  {"U+1F32F", "burrito", "mexican, wrap, burrito"},
  {"U+1F959", "stuffed flatbread", "falafel, flatbread, food, gyro, kebab, stuffed, stuffed flatbread"},
  {"U+1F95A", "egg", "egg, food, egg"},
  {"U+1F373", "cooking", "egg, frying, pan, cooking"},
  {"U+1F958", "shallow pan of food", "casserole, food, paella, pan, shallow, shallow pan of food"},
  {"U+1F372", "pot of food", "pot, stew, pot of food"},
  {"U+1F963", "⊛ bowl with spoon", "breakfast, cereal, congee, oatmeal, porridge, ⊛ bowl with spoon"},
  {"U+1F957", "green salad", "food, green, salad, green salad"},
  {"U+1F37F", "popcorn", "popcorn, popcorn"},
  {"U+1F96B", "⊛ canned food", "can, ⊛ canned food"},
  {"U+1F371", "bento box", "bento, box, bento box"},
  {"U+1F358", "rice cracker", "cracker, rice, rice cracker"},
  {"U+1F359", "rice ball", "ball, Japanese, rice, rice ball"},
  {"U+1F35A", "cooked rice", "cooked, rice, cooked rice"},
  {"U+1F35B", "curry rice", "curry, rice, curry rice"},
  {"U+1F35C", "steaming bowl", "bowl, noodle, ramen, steaming, steaming bowl"},
  {"U+1F35D", "spaghetti", "pasta, spaghetti"},
  {"U+1F360", "roasted sweet potato", "potato, roasted, sweet, roasted sweet potato"},
  {"U+1F362", "oden", "kebab, seafood, skewer, stick, oden"},
  {"U+1F363", "sushi", "sushi, sushi"},
  {"U+1F364", "fried shrimp", "fried, prawn, shrimp, tempura, fried shrimp"},
  {"U+1F365", "fish cake with swirl", "cake, fish, pastry, swirl, fish cake with swirl"},
  {"U+1F361", "dango", "dessert, Japanese, skewer, stick, sweet, dango"},
  {"U+1F95F", "⊛ dumpling", "empanada, gyōza, jiaozi, pierogi, potsticker, ⊛ dumpling"},
  {"U+1F960", "⊛ fortune cookie", "prophecy, ⊛ fortune cookie"},
  {"U+1F961", "⊛ takeout box", "oyster pail, ⊛ takeout box"},
  {"U+1F366", "soft ice cream", "cream, dessert, ice, icecream, soft, sweet, soft ice cream"},
  {"U+1F367", "shaved ice", "dessert, ice, shaved, sweet, shaved ice"},
  {"U+1F368", "ice cream", "cream, dessert, ice, sweet, ice cream"},
  {"U+1F369", "doughnut", "dessert, donut, sweet, doughnut"},
  {"U+1F36A", "cookie", "dessert, sweet, cookie"},
  {"U+1F382", "birthday cake", "birthday, cake, celebration, dessert, pastry, sweet, birthday cake"},
  {"U+1F370", "shortcake", "cake, dessert, pastry, slice, sweet, shortcake"},
  {"U+1F967", "⊛ pie", "filling, pastry, fruit, meat, ⊛ pie"},
  {"U+1F36B", "chocolate bar", "bar, chocolate, dessert, sweet, chocolate bar"},
  {"U+1F36C", "candy", "dessert, sweet, candy"},
  {"U+1F36D", "lollipop", "candy, dessert, sweet, lollipop"},
  {"U+1F36E", "custard", "dessert, pudding, sweet, custard"},
  {"U+1F36F", "honey pot", "honey, honeypot, pot, sweet, honey pot"},
  {"U+1F37C", "baby bottle", "baby, bottle, drink, milk, baby bottle"},
  {"U+1F95B", "glass of milk", "drink, glass, milk, glass of milk"},
  {"U+2615", "hot beverage", "beverage, coffee, drink, hot, steaming, tea, hot beverage"},
  {"U+1F375", "teacup without handle", "beverage, cup, drink, tea, teacup, teacup without handle"},
  {"U+1F376", "sake", "bar, beverage, bottle, cup, drink, sake"},
  {"U+1F37E", "bottle with popping cork", "bar, bottle, cork, drink, popping, bottle with popping cork"},
  {"U+1F377", "wine glass", "bar, beverage, drink, glass, wine, wine glass"},
  {"U+1F378", "cocktail glass", "bar, cocktail, drink, glass, cocktail glass"},
  {"U+1F379", "tropical drink", "bar, drink, tropical, tropical drink"},
  {"U+1F37A", "beer mug", "bar, beer, drink, mug, beer mug"},
  {"U+1F37B", "clinking beer mugs", "bar, beer, clink, drink, mug, clinking beer mugs"},
  {"U+1F942", "clinking glasses", "celebrate, clink, drink, glass, clinking glasses"},
  {"U+1F943", "tumbler glass", "glass, liquor, shot, tumbler, whisky, tumbler glass"},
  {"U+1F964", "⊛ cup with straw", "juice, soda, malt, soft drink, water, ⊛ cup with straw"},
  {"U+1F962", "⊛ chopsticks", "hashi, jeotgarak, kuaizi, ⊛ chopsticks"},
  {"U+1F37D", "fork and knife with plate", "cooking, fork, knife, plate, fork and knife with plate"},
  {"U+1F374", "fork and knife", "cooking, fork, knife, fork and knife"},
  {"U+1F944", "spoon", "spoon, tableware, spoon"},
  {"U+1F52A", "kitchen knife", "cooking, hocho, knife, tool, weapon, kitchen knife"},
  {"U+1F3FA", "amphora", "Aquarius, cooking, drink, jug, tool, weapon, zodiac, amphora"},
  {"U+1F30D", "globe showing Europe-Africa", "Africa, earth, Europe, globe, world, globe showing Europe-Africa"},
  {"U+1F30E", "globe showing Americas", "Americas, earth, globe, world, globe showing Americas"},
  {"U+1F30F", "globe showing Asia-Australia", "Asia, Australia, earth, globe, world, globe showing Asia-Australia"},
  {"U+1F310", "globe with meridians", "earth, globe, meridians, world, globe with meridians"},
  {"U+1F5FA", "world map", "map, world, world map"},
  {"U+1F5FE", "map of Japan", "Japan, map, map of Japan"},
  {"U+1F3D4", "snow-capped mountain", "cold, mountain, snow, snow-capped mountain"},
  {"U+26F0", "mountain", "mountain, mountain"},
  {"U+1F30B", "volcano", "eruption, mountain, volcano"},
  {"U+1F5FB", "mount fuji", "fuji, mountain, mount fuji"},
  {"U+1F3D5", "camping", "camping, camping"},
  {"U+1F3D6", "beach with umbrella", "beach, umbrella, beach with umbrella"},
  {"U+1F3DC", "desert", "desert, desert"},
  {"U+1F3DD", "desert island", "desert, island, desert island"},
  {"U+1F3DE", "national park", "park, national park"},
  {"U+1F3DF", "stadium", "stadium, stadium"},
  {"U+1F3DB", "classical building", "classical, classical building"},
  {"U+1F3D7", "building construction", "construction, building construction"},
  {"U+1F3D8", "houses", "houses, houses"},
  {"U+1F3D9", "cityscape", "city, cityscape"},
  {"U+1F3DA", "derelict house", "derelict, house, derelict house"},
  {"U+1F3E0", "house", "home, house, house"},
  {"U+1F3E1", "house with garden", "garden, home, house, house with garden"},
  {"U+1F3E2", "office building", "building, office building"},
  {"U+1F3E3", "Japanese post office", "Japanese, post, Japanese post office"},
  {"U+1F3E4", "post office", "European, post, post office"},
  {"U+1F3E5", "hospital", "doctor, medicine, hospital"},
  {"U+1F3E6", "bank", "building, bank"},
  {"U+1F3E8", "hotel", "building, hotel"},
  {"U+1F3E9", "love hotel", "hotel, love, love hotel"},
  {"U+1F3EA", "convenience store", "convenience, store, convenience store"},
  {"U+1F3EB", "school", "building, school"},
  {"U+1F3EC", "department store", "department, store, department store"},
  {"U+1F3ED", "factory", "building, factory"},
  {"U+1F3EF", "Japanese castle", "castle, Japanese, Japanese castle"},
  {"U+1F3F0", "castle", "European, castle"},
  {"U+1F492", "wedding", "chapel, romance, wedding"},
  {"U+1F5FC", "Tokyo tower", "Tokyo, tower, Tokyo tower"},
  {"U+1F5FD", "Statue of Liberty", "liberty, statue, Statue of Liberty"},
  {"U+26EA", "church", "Christian, cross, religion, church"},
  {"U+1F54C", "mosque", "islam, Muslim, religion, mosque"},
  {"U+1F54D", "synagogue", "Jew, Jewish, religion, temple, synagogue"},
  {"U+26E9", "shinto shrine", "religion, shinto, shrine, shinto shrine"},
  {"U+1F54B", "kaaba", "islam, Muslim, religion, kaaba"},
  {"U+26F2", "fountain", "fountain, fountain"},
  {"U+26FA", "tent", "camping, tent"},
  {"U+1F301", "foggy", "fog, foggy"},
  {"U+1F303", "night with stars", "night, star, night with stars"},
  {"U+1F304", "sunrise over mountains", "morning, mountain, sun, sunrise, sunrise over mountains"},
  {"U+1F305", "sunrise", "morning, sun, sunrise"},
  {"U+1F306", "cityscape at dusk", "city, dusk, evening, landscape, sun, sunset, cityscape at dusk"},
  {"U+1F307", "sunset", "dusk, sun, sunset"},
  {"U+1F309", "bridge at night", "bridge, night, bridge at night"},
  {"U+2668", "hot springs", "hot, hotsprings, springs, steaming, hot springs"},
  {"U+1F30C", "milky way", "space, milky way"},
  {"U+1F3A0", "carousel horse", "carousel, horse, carousel horse"},
  {"U+1F3A1", "ferris wheel", "amusement park, ferris, wheel, ferris wheel"},
  {"U+1F3A2", "roller coaster", "amusement park, coaster, roller, roller coaster"},
  {"U+1F488", "barber pole", "barber, haircut, pole, barber pole"},
  {"U+1F3AA", "circus tent", "circus, tent, circus tent"},
  {"U+1F3AD", "performing arts", "art, mask, performing, theater, theatre, performing arts"},
  {"U+1F5BC", "framed picture", "art, frame, museum, painting, picture, framed picture"},
  {"U+1F3A8", "artist palette", "art, museum, painting, palette, artist palette"},
  {"U+1F3B0", "slot machine", "game, slot, slot machine"},
  {"U+1F682", "locomotive", "engine, railway, steam, train, locomotive"},
  {"U+1F683", "railway car", "car, electric, railway, train, tram, trolleybus, railway car"},
  {"U+1F684", "high-speed train", "railway, shinkansen, speed, train, high-speed train"},
  {"U+1F685", "bullet train", "bullet, railway, shinkansen, speed, train, bullet train"},
  {"U+1F686", "train", "railway, train"},
  {"U+1F687", "metro", "subway, metro"},
  {"U+1F688", "light rail", "railway, light rail"},
  {"U+1F689", "station", "railway, train, station"},
  {"U+1F68A", "tram", "trolleybus, tram"},
  {"U+1F69D", "monorail", "vehicle, monorail"},
  {"U+1F69E", "mountain railway", "car, mountain, railway, mountain railway"},
  {"U+1F68B", "tram car", "car, tram, trolleybus, tram car"},
  {"U+1F68C", "bus", "vehicle, bus"},
  {"U+1F68D", "oncoming bus", "bus, oncoming, oncoming bus"},
  {"U+1F68E", "trolleybus", "bus, tram, trolley, trolleybus"},
  {"U+1F690", "minibus", "bus, minibus"},
  {"U+1F691", "ambulance", "vehicle, ambulance"},
  {"U+1F692", "fire engine", "engine, fire, truck, fire engine"},
  {"U+1F693", "police car", "car, patrol, police, police car"},
  {"U+1F694", "oncoming police car", "car, oncoming, police, oncoming police car"},
  {"U+1F695", "taxi", "vehicle, taxi"},
  {"U+1F696", "oncoming taxi", "oncoming, taxi, oncoming taxi"},
  {"U+1F697", "automobile", "car, automobile"},
  {"U+1F698", "oncoming automobile", "automobile, car, oncoming, oncoming automobile"},
  {"U+1F699", "sport utility vehicle", "recreational, sport utility, sport utility vehicle"},
  {"U+1F69A", "delivery truck", "delivery, truck, delivery truck"},
  {"U+1F69B", "articulated lorry", "lorry, semi, truck, articulated lorry"},
  {"U+1F69C", "tractor", "vehicle, tractor"},
  {"U+1F6B2", "bicycle", "bike, bicycle"},
  {"U+1F6F4", "kick scooter", "kick, scooter, kick scooter"},
  {"U+1F6F5", "motor scooter", "motor, scooter, motor scooter"},
  {"U+1F68F", "bus stop", "bus, busstop, stop, bus stop"},
  {"U+1F6E3", "motorway", "highway, road, motorway"},
  {"U+1F6E4", "railway track", "railway, train, railway track"},
  {"U+26FD", "fuel pump", "fuel, fuelpump, gas, pump, station, fuel pump"},
  {"U+1F6A8", "police car light", "beacon, car, light, police, revolving, police car light"},
  {"U+1F6A5", "horizontal traffic light", "light, signal, traffic, horizontal traffic light"},
  {"U+1F6A6", "vertical traffic light", "light, signal, traffic, vertical traffic light"},
  {"U+1F6A7", "construction", "barrier, construction"},
  {"U+1F6D1", "stop sign", "octagonal, sign, stop, stop sign"},
  {"U+2693", "anchor", "ship, tool, anchor"},
  {"U+26F5", "sailboat", "boat, resort, sea, yacht, sailboat"},
  {"U+1F6F6", "canoe", "boat, canoe, canoe"},
  {"U+1F6A4", "speedboat", "boat, speedboat"},
  {"U+1F6F3", "passenger ship", "passenger, ship, passenger ship"},
  {"U+26F4", "ferry", "boat, passenger, ferry"},
  {"U+1F6E5", "motor boat", "boat, motorboat, motor boat"},
  {"U+1F6A2", "ship", "boat, passenger, ship"},
  {"U+2708", "airplane", "aeroplane, airplane, airplane"},
  {"U+1F6E9", "small airplane", "aeroplane, airplane, small airplane"},
  {"U+1F6EB", "airplane departure", "aeroplane, airplane, check-in, departure, departures, airplane departure"},
  {"U+1F6EC", "airplane arrival", "aeroplane, airplane, arrivals, arriving, landing, airplane arrival"},
  {"U+1F4BA", "seat", "chair, seat"},
  {"U+1F681", "helicopter", "vehicle, helicopter"},
  {"U+1F69F", "suspension railway", "railway, suspension, suspension railway"},
  {"U+1F6A0", "mountain cableway", "cable, gondola, mountain, mountain cableway"},
  {"U+1F6A1", "aerial tramway", "aerial, cable, car, gondola, tramway, aerial tramway"},
  {"U+1F6F0", "satellite", "space, satellite"},
  {"U+1F680", "rocket", "space, rocket"},
  {"U+1F6F8", "⊛ flying saucer", "UFO, ⊛ flying saucer"},
  {"U+1F6CE", "bellhop bell", "bell, bellhop, hotel, bellhop bell"},
  {"U+1F6AA", "door", "door, door"},
  {"U+1F6CF", "bed", "hotel, sleep, bed"},
  {"U+1F6CB", "couch and lamp", "couch, hotel, lamp, couch and lamp"},
  {"U+1F6BD", "toilet", "toilet, toilet"},
  {"U+1F6BF", "shower", "water, shower"},
  {"U+1F6C1", "bathtub", "bath, bathtub"},
  {"U+231B", "hourglass done", "sand, timer, hourglass done"},
  {"U+23F3", "hourglass not done", "hourglass, sand, timer, hourglass not done"},
  {"U+231A", "watch", "clock, watch"},
  {"U+23F0", "alarm clock", "alarm, clock, alarm clock"},
  {"U+23F1", "stopwatch", "clock, stopwatch"},
  {"U+23F2", "timer clock", "clock, timer, timer clock"},
  {"U+1F570", "mantelpiece clock", "clock, mantelpiece clock"},
  {"U+1F55B", "twelve o’clock", "00, 12, 12:00, clock, o’clock, twelve, twelve o’clock"},
  {"U+1F567", "twelve-thirty", "12, 12:30, 30, clock, thirty, twelve, twelve-thirty"},
  {"U+1F550", "one o’clock", "00, 1, 1:00, clock, o’clock, one, one o’clock"},
  {"U+1F55C", "one-thirty", "1, 1:30, 30, clock, one, thirty, one-thirty"},
  {"U+1F551", "two o’clock", "00, 2, 2:00, clock, o’clock, two, two o’clock"},
  {"U+1F55D", "two-thirty", "2, 2:30, 30, clock, thirty, two, two-thirty"},
  {"U+1F552", "three o’clock", "00, 3, 3:00, clock, o’clock, three, three o’clock"},
  {"U+1F55E", "three-thirty", "3, 3:30, 30, clock, thirty, three, three-thirty"},
  {"U+1F553", "four o’clock", "00, 4, 4:00, clock, four, o’clock, four o’clock"},
  {"U+1F55F", "four-thirty", "30, 4, 4:30, clock, four, thirty, four-thirty"},
  {"U+1F554", "five o’clock", "00, 5, 5:00, clock, five, o’clock, five o’clock"},
  {"U+1F560", "five-thirty", "30, 5, 5:30, clock, five, thirty, five-thirty"},
  {"U+1F555", "six o’clock", "00, 6, 6:00, clock, o’clock, six, six o’clock"},
  {"U+1F561", "six-thirty", "30, 6, 6:30, clock, six, thirty, six-thirty"},
  {"U+1F556", "seven o’clock", "00, 7, 7:00, clock, o’clock, seven, seven o’clock"},
  {"U+1F562", "seven-thirty", "30, 7, 7:30, clock, seven, thirty, seven-thirty"},
  {"U+1F557", "eight o’clock", "00, 8, 8:00, clock, eight, o’clock, eight o’clock"},
  {"U+1F563", "eight-thirty", "30, 8, 8:30, clock, eight, thirty, eight-thirty"},
  {"U+1F558", "nine o’clock", "00, 9, 9:00, clock, nine, o’clock, nine o’clock"},
  {"U+1F564", "nine-thirty", "30, 9, 9:30, clock, nine, thirty, nine-thirty"},
  {"U+1F559", "ten o’clock", "00, 10, 10:00, clock, o’clock, ten, ten o’clock"},
  {"U+1F565", "ten-thirty", "10, 10:30, 30, clock, ten, thirty, ten-thirty"},
  {"U+1F55A", "eleven o’clock", "00, 11, 11:00, clock, eleven, o’clock, eleven o’clock"},
  {"U+1F566", "eleven-thirty", "11, 11:30, 30, clock, eleven, thirty, eleven-thirty"},
  {"U+1F311", "new moon", "dark, moon, new moon"},
  {"U+1F312", "waxing crescent moon", "crescent, moon, waxing, waxing crescent moon"},
  {"U+1F313", "first quarter moon", "moon, quarter, first quarter moon"},
  {"U+1F314", "waxing gibbous moon", "gibbous, moon, waxing, waxing gibbous moon"},
  {"U+1F315", "full moon", "full, moon, full moon"},
  {"U+1F316", "waning gibbous moon", "gibbous, moon, waning, waning gibbous moon"},
  {"U+1F317", "last quarter moon", "moon, quarter, last quarter moon"},
  {"U+1F318", "waning crescent moon", "crescent, moon, waning, waning crescent moon"},
  {"U+1F319", "crescent moon", "crescent, moon, crescent moon"},
  {"U+1F31A", "new moon face", "face, moon, new moon face"},
  {"U+1F31B", "first quarter moon face", "face, moon, quarter, first quarter moon face"},
  {"U+1F31C", "last quarter moon face", "face, moon, quarter, last quarter moon face"},
  {"U+1F321", "thermometer", "weather, thermometer"},
  {"U+2600", "sun", "bright, rays, sunny, sun"},
  {"U+1F31D", "full moon face", "bright, face, full, moon, full moon face"},
  {"U+1F31E", "sun with face", "bright, face, sun, sun with face"},
  {"U+2B50", "white medium star", "star, white medium star"},
  {"U+1F31F", "glowing star", "glittery, glow, shining, sparkle, star, glowing star"},
  {"U+1F320", "shooting star", "falling, shooting, star, shooting star"},
  {"U+2601", "cloud", "weather, cloud"},
  {"U+26C5", "sun behind cloud", "cloud, sun, sun behind cloud"},
  {"U+26C8", "cloud with lightning and rain", "cloud, rain, thunder, cloud with lightning and rain"},
  {"U+1F324", "sun behind small cloud", "cloud, sun, sun behind small cloud"},
  {"U+1F325", "sun behind large cloud", "cloud, sun, sun behind large cloud"},
  {"U+1F326", "sun behind rain cloud", "cloud, rain, sun, sun behind rain cloud"},
  {"U+1F327", "cloud with rain", "cloud, rain, cloud with rain"},
  {"U+1F328", "cloud with snow", "cloud, cold, snow, cloud with snow"},
  {"U+1F329", "cloud with lightning", "cloud, lightning, cloud with lightning"},
  {"U+1F32A", "tornado", "cloud, whirlwind, tornado"},
  {"U+1F32B", "fog", "cloud, fog"},
  {"U+1F32C", "wind face", "blow, cloud, face, wind, wind face"},
  {"U+1F300", "cyclone", "dizzy, twister, typhoon, cyclone"},
  {"U+1F308", "rainbow", "rain, rainbow"},
  {"U+1F302", "closed umbrella", "clothing, rain, umbrella, closed umbrella"},
  {"U+2602", "umbrella", "clothing, rain, umbrella"},
  {"U+2614", "umbrella with rain drops", "clothing, drop, rain, umbrella, umbrella with rain drops"},
  {"U+26F1", "umbrella on ground", "rain, sun, umbrella, umbrella on ground"},
  {"U+26A1", "high voltage", "danger, electric, electricity, lightning, voltage, zap, high voltage"},
  {"U+2744", "snowflake", "cold, snow, snowflake"},
  {"U+2603", "snowman", "cold, snow, snowman"},
  {"U+26C4", "snowman without snow", "cold, snow, snowman, snowman without snow"},
  {"U+2604", "comet", "space, comet"},
  {"U+1F525", "fire", "flame, tool, fire"},
  {"U+1F4A7", "droplet", "cold, comic, drop, sweat, droplet"},
  {"U+1F30A", "water wave", "ocean, water, wave, water wave"},
  {"U+1F383", "jack-o-lantern", "celebration, halloween, jack, lantern, jack-o-lantern"},
  {"U+1F384", "Christmas tree", "celebration, Christmas, tree, Christmas tree"},
  {"U+1F386", "fireworks", "celebration, fireworks"},
  {"U+1F387", "sparkler", "celebration, fireworks, sparkle, sparkler"},
  {"U+2728", "sparkles", "sparkle, star, sparkles"},
  {"U+1F388", "balloon", "celebration, balloon"},
  {"U+1F389", "party popper", "celebration, party, popper, tada, party popper"},
  {"U+1F38A", "confetti ball", "ball, celebration, confetti, confetti ball"},
  {"U+1F38B", "tanabata tree", "banner, celebration, Japanese, tree, tanabata tree"},
  {"U+1F38D", "pine decoration", "bamboo, celebration, Japanese, pine, pine decoration"},
  {"U+1F38E", "Japanese dolls", "celebration, doll, festival, Japanese, Japanese dolls"},
  {"U+1F38F", "carp streamer", "carp, celebration, streamer, carp streamer"},
  {"U+1F390", "wind chime", "bell, celebration, chime, wind, wind chime"},
  {"U+1F391", "moon viewing ceremony", "celebration, ceremony, moon, moon viewing ceremony"},
  {"U+1F380", "ribbon", "celebration, ribbon"},
  {"U+1F381", "wrapped gift", "box, celebration, gift, present, wrapped, wrapped gift"},
  {"U+1F397", "reminder ribbon", "celebration, reminder, ribbon, reminder ribbon"},
  {"U+1F39F", "admission tickets", "admission, ticket, admission tickets"},
  {"U+1F3AB", "ticket", "admission, ticket"},
  {"U+1F396", "military medal", "celebration, medal, military, military medal"},
  {"U+1F3C6", "trophy", "prize, trophy"},
  {"U+1F3C5", "sports medal", "medal, sports medal"},
  {"U+1F947", "1st place medal", "first, gold, medal, 1st place medal"},
  {"U+1F948", "2nd place medal", "medal, second, silver, 2nd place medal"},
  {"U+1F949", "3rd place medal", "bronze, medal, third, 3rd place medal"},
  {"U+26BD", "soccer ball", "ball, football, soccer, soccer ball"},
  {"U+26BE", "baseball", "ball, baseball"},
  {"U+1F3C0", "basketball", "ball, hoop, basketball"},
  {"U+1F3D0", "volleyball", "ball, game, volleyball"},
  {"U+1F3C8", "american football", "american, ball, football, american football"},
  {"U+1F3C9", "rugby football", "ball, football, rugby, rugby football"},
  {"U+1F3BE", "tennis", "ball, racquet, tennis"},
  {"U+1F3B1", "pool 8 ball", "8, 8 ball, ball, billiard, eight, game, pool 8 ball"},
  {"U+1F3B3", "bowling", "ball, game, bowling"},
  {"U+1F3CF", "cricket game", "ball, bat, game, cricket game"},
  {"U+1F3D1", "field hockey", "ball, field, game, hockey, stick, field hockey"},
  {"U+1F3D2", "ice hockey", "game, hockey, ice, puck, stick, ice hockey"},
  {"U+1F3D3", "ping pong", "ball, bat, game, paddle, ping pong, table tennis, ping pong"},
  {"U+1F3F8", "badminton", "birdie, game, racquet, shuttlecock, badminton"},
  {"U+1F94A", "boxing glove", "boxing, glove, boxing glove"},
  {"U+1F94B", "martial arts uniform", "judo, karate, martial arts, taekwondo, uniform, martial arts uniform"},
  {"U+1F945", "goal net", "goal, net, goal net"},
  {"U+1F3AF", "direct hit", "bull, bullseye, dart, eye, game, hit, target, direct hit"},
  {"U+26F3", "flag in hole", "golf, hole, flag in hole"},
  {"U+26F8", "ice skate", "ice, skate, ice skate"},
  {"U+1F3A3", "fishing pole", "fish, pole, fishing pole"},
  {"U+1F3BD", "running shirt", "athletics, running, sash, shirt, running shirt"},
  {"U+1F3BF", "skis", "ski, snow, skis"},
  {"U+1F6F7", "⊛ sled", "sledge, sleigh, luge, toboggan, ⊛ sled"},
  {"U+1F94C", "⊛ curling stone", "game, rock, ⊛ curling stone"},
  {"U+1F3AE", "video game", "controller, game, video game"},
  {"U+1F579", "joystick", "game, video game, joystick"},
  {"U+1F3B2", "game die", "dice, die, game, game die"},
  {"U+2660", "spade suit", "card, game, spade suit"},
  {"U+2665", "heart suit", "card, game, heart suit"},
  {"U+2666", "diamond suit", "card, game, diamond suit"},
  {"U+2663", "club suit", "card, game, club suit"},
  {"U+1F0CF", "joker", "card, game, wildcard, joker"},
  {"U+1F004", "mahjong red dragon", "game, mahjong, red, mahjong red dragon"},
  {"U+1F3B4", "flower playing cards", "card, flower, game, Japanese, playing, flower playing cards"},
  {"U+1F507", "muted speaker", "mute, quiet, silent, speaker, muted speaker"},
  {"U+1F508", "speaker low volume", "soft, speaker low volume"},
  {"U+1F509", "speaker medium volume", "medium, speaker medium volume"},
  {"U+1F50A", "speaker high volume", "loud, speaker high volume"},
  {"U+1F4E2", "loudspeaker", "loud, public address, loudspeaker"},
  {"U+1F4E3", "megaphone", "cheering, megaphone"},
  {"U+1F4EF", "postal horn", "horn, post, postal, postal horn"},
  {"U+1F514", "bell", "bell, bell"},
  {"U+1F515", "bell with slash", "bell, forbidden, mute, no, not, prohibited, quiet, silent, bell with slash"},
  {"U+1F3BC", "musical score", "music, score, musical score"},
  {"U+1F3B5", "musical note", "music, note, musical note"},
  {"U+1F3B6", "musical notes", "music, note, notes, musical notes"},
  {"U+1F399", "studio microphone", "mic, microphone, music, studio, studio microphone"},
  {"U+1F39A", "level slider", "level, music, slider, level slider"},
  {"U+1F39B", "control knobs", "control, knobs, music, control knobs"},
  {"U+1F3A4", "microphone", "karaoke, mic, microphone"},
  {"U+1F3A7", "headphone", "earbud, headphone"},
  {"U+1F4FB", "radio", "video, radio"},
  {"U+1F3B7", "saxophone", "instrument, music, sax, saxophone"},
  {"U+1F3B8", "guitar", "instrument, music, guitar"},
  {"U+1F3B9", "musical keyboard", "instrument, keyboard, music, piano, musical keyboard"},
  {"U+1F3BA", "trumpet", "instrument, music, trumpet"},
  {"U+1F3BB", "violin", "instrument, music, violin"},
  {"U+1F941", "drum", "drum, drumsticks, music, drum"},
  {"U+1F4F1", "mobile phone", "cell, mobile, phone, telephone, mobile phone"},
  {"U+1F4F2", "mobile phone with arrow", "arrow, call, cell, mobile, phone, receive, telephone, mobile phone with arrow"},
  {"U+260E", "telephone", "phone, telephone"},
  {"U+1F4DE", "telephone receiver", "phone, receiver, telephone, telephone receiver"},
  {"U+1F4DF", "pager", "pager, pager"},
  {"U+1F4E0", "fax machine", "fax, fax machine"},
  {"U+1F50B", "battery", "battery, battery"},
  {"U+1F50C", "electric plug", "electric, electricity, plug, electric plug"},
  {"U+1F4BB", "laptop computer", "computer, pc, personal, laptop computer"},
  {"U+1F5A5", "desktop computer", "computer, desktop, desktop computer"},
  {"U+1F5A8", "printer", "computer, printer"},
  {"U+2328", "keyboard", "computer, keyboard"},
  {"U+1F5B1", "computer mouse", "computer, computer mouse"},
  {"U+1F5B2", "trackball", "computer, trackball"},
  {"U+1F4BD", "computer disk", "computer, disk, minidisk, optical, computer disk"},
  {"U+1F4BE", "floppy disk", "computer, disk, floppy, floppy disk"},
  {"U+1F4BF", "optical disk", "cd, computer, disk, optical, optical disk"},
  {"U+1F4C0", "dvd", "blu-ray, computer, disk, dvd, optical, dvd"},
  {"U+1F3A5", "movie camera", "camera, cinema, movie, movie camera"},
  {"U+1F39E", "film frames", "cinema, film, frames, movie, film frames"},
  {"U+1F4FD", "film projector", "cinema, film, movie, projector, video, film projector"},
  {"U+1F3AC", "clapper board", "clapper, movie, clapper board"},
  {"U+1F4FA", "television", "tv, video, television"},
  {"U+1F4F7", "camera", "video, camera"},
  {"U+1F4F8", "camera with flash", "camera, flash, video, camera with flash"},
  {"U+1F4F9", "video camera", "camera, video, video camera"},
  {"U+1F4FC", "videocassette", "tape, vhs, video, videocassette"},
  {"U+1F50D", "magnifying glass tilted left", "glass, magnifying, search, tool, magnifying glass tilted left"},
  {"U+1F50E", "magnifying glass tilted right", "glass, magnifying, search, tool, magnifying glass tilted right"},
  {"U+1F52C", "microscope", "science, tool, microscope"},
  {"U+1F52D", "telescope", "science, tool, telescope"},
  {"U+1F4E1", "satellite antenna", "antenna, dish, satellite, satellite antenna"},
  {"U+1F56F", "candle", "light, candle"},
  {"U+1F4A1", "light bulb", "bulb, comic, electric, idea, light, light bulb"},
  {"U+1F526", "flashlight", "electric, light, tool, torch, flashlight"},
  {"U+1F3EE", "red paper lantern", "bar, lantern, light, red, red paper lantern"},
  {"U+1F4D4", "notebook with decorative cover", "book, cover, decorated, notebook, notebook with decorative cover"},
  {"U+1F4D5", "closed book", "book, closed, closed book"},
  {"U+1F4D6", "open book", "book, open, open book"},
  {"U+1F4D7", "green book", "book, green, green book"},
  {"U+1F4D8", "blue book", "blue, book, blue book"},
  {"U+1F4D9", "orange book", "book, orange, orange book"},
  {"U+1F4DA", "books", "book, books"},
  {"U+1F4D3", "notebook", "notebook, notebook"},
  {"U+1F4D2", "ledger", "notebook, ledger"},
  {"U+1F4C3", "page with curl", "curl, document, page, page with curl"},
  {"U+1F4DC", "scroll", "paper, scroll"},
  {"U+1F4C4", "page facing up", "document, page, page facing up"},
  {"U+1F4F0", "newspaper", "news, paper, newspaper"},
  {"U+1F5DE", "rolled-up newspaper", "news, newspaper, paper, rolled, rolled-up newspaper"},
  {"U+1F4D1", "bookmark tabs", "bookmark, mark, marker, tabs, bookmark tabs"},
  {"U+1F516", "bookmark", "mark, bookmark"},
  {"U+1F3F7", "label", "label, label"},
  {"U+1F4B0", "money bag", "bag, dollar, money, moneybag, money bag"},
  {"U+1F4B4", "yen banknote", "bank, banknote, bill, currency, money, note, yen, yen banknote"},
  {"U+1F4B5", "dollar banknote", "bank, banknote, bill, currency, dollar, money, note, dollar banknote"},
  {"U+1F4B6", "euro banknote", "bank, banknote, bill, currency, euro, money, note, euro banknote"},
  {"U+1F4B7", "pound banknote", "bank, banknote, bill, currency, money, note, pound, pound banknote"},
  {"U+1F4B8", "money with wings", "bank, banknote, bill, dollar, fly, money, note, wings, money with wings"},
  {"U+1F4B3", "credit card", "bank, card, credit, money, credit card"},
  {"U+1F4B9", "chart increasing with yen", "bank, chart, currency, graph, growth, market, money, rise, trend, upward, yen, chart increasing with yen"},
  {"U+1F4B1", "currency exchange", "bank, currency, exchange, money, currency exchange"},
  {"U+1F4B2", "heavy dollar sign", "currency, dollar, money, heavy dollar sign"},
  {"U+2709", "envelope", "email, letter, envelope"},
  {"U+1F4E7", "e-mail", "email, letter, mail, e-mail"},
  {"U+1F4E8", "incoming envelope", "e-mail, email, envelope, incoming, letter, mail, receive, incoming envelope"},
  {"U+1F4E9", "envelope with arrow", "arrow, down, e-mail, email, envelope, letter, mail, outgoing, sent, envelope with arrow"},
  {"U+1F4E4", "outbox tray", "box, letter, mail, outbox, sent, tray, outbox tray"},
  {"U+1F4E5", "inbox tray", "box, inbox, letter, mail, receive, tray, inbox tray"},
  {"U+1F4E6", "package", "box, parcel, package"},
  {"U+1F4EB", "closed mailbox with raised flag", "closed, mail, mailbox, postbox, closed mailbox with raised flag"},
  {"U+1F4EA", "closed mailbox with lowered flag", "closed, lowered, mail, mailbox, postbox, closed mailbox with lowered flag"},
  {"U+1F4EC", "open mailbox with raised flag", "mail, mailbox, open, postbox, open mailbox with raised flag"},
  {"U+1F4ED", "open mailbox with lowered flag", "lowered, mail, mailbox, open, postbox, open mailbox with lowered flag"},
  {"U+1F4EE", "postbox", "mail, mailbox, postbox"},
  {"U+1F5F3", "ballot box with ballot", "ballot, box, ballot box with ballot"},
  {"U+270F", "pencil", "pencil, pencil"},
  {"U+2712", "black nib", "nib, pen, black nib"},
  {"U+1F58B", "fountain pen", "fountain, pen, fountain pen"},
  {"U+1F58A", "pen", "ballpoint, pen"},
  {"U+1F58C", "paintbrush", "painting, paintbrush"},
  {"U+1F58D", "crayon", "crayon, crayon"},
  {"U+1F4DD", "memo", "pencil, memo"},
  {"U+1F4BC", "briefcase", "briefcase, briefcase"},
  {"U+1F4C1", "file folder", "file, folder, file folder"},
  {"U+1F4C2", "open file folder", "file, folder, open, open file folder"},
  {"U+1F5C2", "card index dividers", "card, dividers, index, card index dividers"},
  {"U+1F4C5", "calendar", "date, calendar"},
  {"U+1F4C6", "tear-off calendar", "calendar, tear-off calendar"},
  {"U+1F5D2", "spiral notepad", "note, pad, spiral, spiral notepad"},
  {"U+1F5D3", "spiral calendar", "calendar, pad, spiral, spiral calendar"},
  {"U+1F4C7", "card index", "card, index, rolodex, card index"},
  {"U+1F4C8", "chart increasing", "chart, graph, growth, trend, upward, chart increasing"},
  {"U+1F4C9", "chart decreasing", "chart, down, graph, trend, chart decreasing"},
  {"U+1F4CA", "bar chart", "bar, chart, graph, bar chart"},
  {"U+1F4CB", "clipboard", "clipboard, clipboard"},
  {"U+1F4CC", "pushpin", "pin, pushpin"},
  {"U+1F4CD", "round pushpin", "pin, pushpin, round pushpin"},
  {"U+1F4CE", "paperclip", "paperclip, paperclip"},
  {"U+1F587", "linked paperclips", "link, paperclip, linked paperclips"},
  {"U+1F4CF", "straight ruler", "ruler, straight edge, straight ruler"},
  {"U+1F4D0", "triangular ruler", "ruler, set, triangle, triangular ruler"},
  {"U+2702", "scissors", "cutting, tool, scissors"},
  {"U+1F5C3", "card file box", "box, card, file, card file box"},
  {"U+1F5C4", "file cabinet", "cabinet, file, filing, file cabinet"},
  {"U+1F5D1", "wastebasket", "wastebasket, wastebasket"},
  {"U+1F512", "locked", "closed, locked"},
  {"U+1F513", "unlocked", "lock, open, unlock, unlocked"},
  {"U+1F50F", "locked with pen", "ink, lock, nib, pen, privacy, locked with pen"},
  {"U+1F510", "locked with key", "closed, key, lock, secure, locked with key"},
  {"U+1F511", "key", "lock, password, key"},
  {"U+1F5DD", "old key", "clue, key, lock, old, old key"},
  {"U+1F528", "hammer", "tool, hammer"},
  {"U+26CF", "pick", "mining, tool, pick"},
  {"U+2692", "hammer and pick", "hammer, pick, tool, hammer and pick"},
  {"U+1F6E0", "hammer and wrench", "hammer, spanner, tool, wrench, hammer and wrench"},
  {"U+1F5E1", "dagger", "knife, weapon, dagger"},
  {"U+2694", "crossed swords", "crossed, swords, weapon, crossed swords"},
  {"U+1F52B", "pistol", "gun, handgun, revolver, tool, weapon, pistol"},
  {"U+1F3F9", "bow and arrow", "archer, archery, arrow, bow, Sagittarius, tool, weapon, zodiac, bow and arrow"},
  {"U+1F6E1", "shield", "weapon, shield"},
  {"U+1F527", "wrench", "spanner, tool, wrench, wrench"},
  {"U+1F529", "nut and bolt", "bolt, nut, tool, nut and bolt"},
  {"U+2699", "gear", "tool, gear"},
  {"U+1F5DC", "clamp", "compress, tool, vice, clamp"},
  {"U+2697", "alembic", "chemistry, tool, alembic"},
  {"U+2696", "balance scale", "balance, justice, Libra, scales, tool, weight, zodiac, balance scale"},
  {"U+1F517", "link", "link, link"},
  {"U+26D3", "chains", "chain, chains"},
  {"U+1F489", "syringe", "doctor, medicine, needle, shot, sick, tool, syringe"},
  {"U+1F48A", "pill", "doctor, medicine, sick, pill"},
  {"U+1F6AC", "cigarette", "smoking, cigarette"},
  {"U+26B0", "coffin", "death, coffin"},
  {"U+26B1", "funeral urn", "ashes, death, funeral, urn, funeral urn"},
  {"U+1F5FF", "moai", "face, moyai, statue, moai"},
  {"U+1F6E2", "oil drum", "drum, oil, oil drum"},
  {"U+1F52E", "crystal ball", "ball, crystal, fairy tale, fantasy, fortune, tool, crystal ball"},
  {"U+1F6D2", "shopping cart", "cart, shopping, trolley, shopping cart"},
  {"U+1F3E7", "ATM sign", "atm, automated, bank, teller, ATM sign"},
  {"U+1F6AE", "litter in bin sign", "litter, litter bin, litter in bin sign"},
  {"U+1F6B0", "potable water", "drinking, potable, water, potable water"},
  {"U+267F", "wheelchair symbol", "access, wheelchair symbol"},
  {"U+1F6B9", "men’s room", "lavatory, man, restroom, wc, men’s room"},
  {"U+1F6BA", "women’s room", "lavatory, restroom, wc, woman, women’s room"},
  {"U+1F6BB", "restroom", "lavatory, restroom, WC, restroom"},
  {"U+1F6BC", "baby symbol", "baby, changing, baby symbol"},
  {"U+1F6BE", "water closet", "closet, lavatory, restroom, water, wc, water closet"},
  {"U+1F6C2", "passport control", "control, passport, passport control"},
  {"U+1F6C3", "customs", "customs, customs"},
  {"U+1F6C4", "baggage claim", "baggage, claim, baggage claim"},
  {"U+1F6C5", "left luggage", "baggage, locker, luggage, left luggage"},
  {"U+26A0", "warning", "warning, warning"},
  {"U+1F6B8", "children crossing", "child, crossing, pedestrian, traffic, children crossing"},
  {"U+26D4", "no entry", "entry, forbidden, no, not, prohibited, traffic, no entry"},
  {"U+1F6AB", "prohibited", "entry, forbidden, no, not, prohibited"},
  {"U+1F6B3", "no bicycles", "bicycle, bike, forbidden, no, not, prohibited, no bicycles"},
  {"U+1F6AD", "no smoking", "forbidden, no, not, prohibited, smoking, no smoking"},
  {"U+1F6AF", "no littering", "forbidden, litter, no, not, prohibited, no littering"},
  {"U+1F6B1", "non-potable water", "non-drinking, non-potable, water, non-potable water"},
  {"U+1F6B7", "no pedestrians", "forbidden, no, not, pedestrian, prohibited, no pedestrians"},
  {"U+1F4F5", "no mobile phones", "cell, forbidden, mobile, no, not, phone, prohibited, telephone, no mobile phones"},
  {"U+1F51E", "no one under eighteen", "18, age restriction, eighteen, forbidden, no, not, prohibited, underage, no one under eighteen"},
  {"U+2622", "radioactive", "radioactive, sign, radioactive"},
  {"U+2623", "biohazard", "biohazard, sign, biohazard"},
  {"U+2B06", "up arrow", "arrow, cardinal, direction, north, up arrow"},
  {"U+2197", "up-right arrow", "arrow, direction, intercardinal, northeast, up-right arrow"},
  {"U+27A1", "right arrow", "arrow, cardinal, direction, east, right arrow"},
  {"U+2198", "down-right arrow", "arrow, direction, intercardinal, southeast, down-right arrow"},
  {"U+2B07", "down arrow", "arrow, cardinal, direction, down, south, down arrow"},
  {"U+2199", "down-left arrow", "arrow, direction, intercardinal, southwest, down-left arrow"},
  {"U+2B05", "left arrow", "arrow, cardinal, direction, west, left arrow"},
  {"U+2196", "up-left arrow", "arrow, direction, intercardinal, northwest, up-left arrow"},
  {"U+2195", "up-down arrow", "arrow, up-down arrow"},
  {"U+2194", "left-right arrow", "arrow, left-right arrow"},
  {"U+21A9", "right arrow curving left", "arrow, right arrow curving left"},
  {"U+21AA", "left arrow curving right", "arrow, left arrow curving right"},
  {"U+2934", "right arrow curving up", "arrow, right arrow curving up"},
  {"U+2935", "right arrow curving down", "arrow, down, right arrow curving down"},
  {"U+1F503", "clockwise vertical arrows", "arrow, clockwise, reload, clockwise vertical arrows"},
  {"U+1F504", "counterclockwise arrows button", "anticlockwise, arrow, counterclockwise, withershins, counterclockwise arrows button"},
  {"U+1F519", "BACK arrow", "arrow, back, BACK arrow"},
  {"U+1F51A", "END arrow", "arrow, end, END arrow"},
  {"U+1F51B", "ON! arrow", "arrow, mark, on, ON! arrow"},
  {"U+1F51C", "SOON arrow", "arrow, soon, SOON arrow"},
  {"U+1F51D", "TOP arrow", "arrow, top, up, TOP arrow"},
  {"U+1F6D0", "place of worship", "religion, worship, place of worship"},
  {"U+269B", "atom symbol", "atheist, atom, atom symbol"},
  {"U+1F549", "om", "Hindu, religion, om"},
  {"U+2721", "star of David", "David, Jew, Jewish, religion, star, star of David"},
  {"U+2638", "wheel of dharma", "Buddhist, dharma, religion, wheel, wheel of dharma"},
  {"U+262F", "yin yang", "religion, tao, taoist, yang, yin, yin yang"},
  {"U+271D", "latin cross", "Christian, cross, religion, latin cross"},
  {"U+2626", "orthodox cross", "Christian, cross, religion, orthodox cross"},
  {"U+262A", "star and crescent", "islam, Muslim, religion, star and crescent"},
  {"U+262E", "peace symbol", "peace, peace symbol"},
  {"U+1F54E", "menorah", "candelabrum, candlestick, religion, menorah"},
  {"U+1F52F", "dotted six-pointed star", "fortune, star, dotted six-pointed star"},
  {"U+2648", "Aries", "ram, zodiac, Aries"},
  {"U+2649", "Taurus", "bull, ox, zodiac, Taurus"},
  {"U+264A", "Gemini", "twins, zodiac, Gemini"},
  {"U+264B", "Cancer", "crab, zodiac, Cancer"},
  {"U+264C", "Leo", "lion, zodiac, Leo"},
  {"U+264D", "Virgo", "zodiac, Virgo"},
  {"U+264E", "Libra", "balance, justice, scales, zodiac, Libra"},
  {"U+264F", "Scorpius", "scorpio, scorpion, zodiac, Scorpius"},
  {"U+2650", "Sagittarius", "archer, zodiac, Sagittarius"},
  {"U+2651", "Capricorn", "goat, zodiac, Capricorn"},
  {"U+2652", "Aquarius", "bearer, water, zodiac, Aquarius"},
  {"U+2653", "Pisces", "fish, zodiac, Pisces"},
  {"U+26CE", "Ophiuchus", "bearer, serpent, snake, zodiac, Ophiuchus"},
  {"U+1F500", "shuffle tracks button", "arrow, crossed, shuffle tracks button"},
  {"U+1F501", "repeat button", "arrow, clockwise, repeat, repeat button"},
  {"U+1F502", "repeat single button", "arrow, clockwise, once, repeat single button"},
  {"U+25B6", "play button", "arrow, play, right, triangle, play button"},
  {"U+23E9", "fast-forward button", "arrow, double, fast, forward, fast-forward button"},
  {"U+23ED", "next track button", "arrow, next scene, next track, triangle, next track button"},
  {"U+23EF", "play or pause button", "arrow, pause, play, right, triangle, play or pause button"},
  {"U+25C0", "reverse button", "arrow, left, reverse, triangle, reverse button"},
  {"U+23EA", "fast reverse button", "arrow, double, rewind, fast reverse button"},
  {"U+23EE", "last track button", "arrow, previous scene, previous track, triangle, last track button"},
  {"U+1F53C", "up button", "arrow, button, red, up button"},
  {"U+23EB", "fast up button", "arrow, double, fast up button"},
  {"U+1F53D", "down button", "arrow, button, down, red, down button"},
  {"U+23EC", "fast down button", "arrow, double, down, fast down button"},
  {"U+23F8", "pause button", "bar, double, pause, vertical, pause button"},
  {"U+23F9", "stop button", "square, stop, stop button"},
  {"U+23FA", "record button", "circle, record, record button"},
  {"U+23CF", "eject button", "eject, eject button"},
  {"U+1F3A6", "cinema", "camera, film, movie, cinema"},
  {"U+1F505", "dim button", "brightness, dim, low, dim button"},
  {"U+1F506", "bright button", "bright, brightness, bright button"},
  {"U+1F4F6", "antenna bars", "antenna, bar, cell, mobile, phone, signal, telephone, antenna bars"},
  {"U+1F4F3", "vibration mode", "cell, mobile, mode, phone, telephone, vibration, vibration mode"},
  {"U+1F4F4", "mobile phone off", "cell, mobile, off, phone, telephone, mobile phone off"},
  {"U+2640", "female sign", "woman, female sign"},
  {"U+2642", "male sign", "man, male sign"},
  {"U+2695", "medical symbol", "aesculapius, medicine, staff, medical symbol"},
  {"U+267B", "recycling symbol", "recycle, recycling symbol"},
  {"U+269C", "fleur-de-lis", "fleur-de-lis, fleur-de-lis"},
  {"U+1F531", "trident emblem", "anchor, emblem, ship, tool, trident, trident emblem"},
  {"U+1F4DB", "name badge", "badge, name, name badge"},
  {"U+1F530", "Japanese symbol for beginner", "beginner, chevron, green, Japanese, leaf, tool, yellow, Japanese symbol for beginner"},
  {"U+2B55", "heavy large circle", "circle, o, heavy large circle"},
  {"U+2705", "white heavy check mark", "check, mark, white heavy check mark"},
  {"U+2611", "ballot box with check", "ballot, box, check, ballot box with check"},
  {"U+2714", "heavy check mark", "check, mark, heavy check mark"},
  {"U+2716", "heavy multiplication x", "cancel, multiplication, multiply, x, heavy multiplication x"},
  {"U+274C", "cross mark", "cancel, mark, multiplication, multiply, x, cross mark"},
  {"U+274E", "cross mark button", "mark, square, cross mark button"},
  {"U+2795", "heavy plus sign", "math, plus, heavy plus sign"},
  {"U+2796", "heavy minus sign", "math, minus, heavy minus sign"},
  {"U+2797", "heavy division sign", "division, math, heavy division sign"},
  {"U+27B0", "curly loop", "curl, loop, curly loop"},
  {"U+27BF", "double curly loop", "curl, double, loop, double curly loop"},
  {"U+303D", "part alternation mark", "mark, part, part alternation mark"},
  {"U+2733", "eight-spoked asterisk", "asterisk, eight-spoked asterisk"},
  {"U+2734", "eight-pointed star", "star, eight-pointed star"},
  {"U+2747", "sparkle", "sparkle, sparkle"},
  {"U+203C", "double exclamation mark", "bangbang, exclamation, mark, punctuation, double exclamation mark"},
  {"U+2049", "exclamation question mark", "exclamation, interrobang, mark, punctuation, question, exclamation question mark"},
  {"U+2753", "question mark", "mark, punctuation, question, question mark"},
  {"U+2754", "white question mark", "mark, outlined, punctuation, question, white question mark"},
  {"U+2755", "white exclamation mark", "exclamation, mark, outlined, punctuation, white exclamation mark"},
  {"U+2757", "exclamation mark", "exclamation, mark, punctuation, exclamation mark"},
  {"U+3030", "wavy dash", "dash, punctuation, wavy, wavy dash"},
  {"U+00A9", "copyright", "copyright, copyright"},
  {"U+00AE", "registered", "registered, registered"},
  {"U+2122", "trade mark", "mark, tm, trademark, trade mark"},
  {"U+1F51F", "keycap 10", "keycap 10, keycap 10"},
  {"U+1F4AF", "hundred points", "100, full, hundred, score, hundred points"},
  {"U+1F520", "input latin uppercase", "ABCD, input, latin, letters, uppercase, input latin uppercase"},
  {"U+1F521", "input latin lowercase", "abcd, input, latin, letters, lowercase, input latin lowercase"},
  {"U+1F522", "input numbers", "1234, input, numbers, input numbers"},
  {"U+1F523", "input symbols", "〒♪&%, input, input symbols"},
  {"U+1F524", "input latin letters", "abc, alphabet, input, latin, letters, input latin letters"},
  {"U+1F170", "A button (blood type)", "a, blood type, A button (blood type)"},
  {"U+1F18E", "AB button (blood type)", "ab, blood type, AB button (blood type)"},
  {"U+1F171", "B button (blood type)", "b, blood type, B button (blood type)"},
  {"U+1F191", "CL button", "cl, CL button"},
  {"U+1F192", "COOL button", "cool, COOL button"},
  {"U+1F193", "FREE button", "free, FREE button"},
  {"U+2139", "information", "i, information, information"},
  {"U+1F194", "ID button", "id, identity, ID button"},
  {"U+24C2", "circled M", "circle, m, circled M"},
  {"U+1F195", "NEW button", "new, NEW button"},
  {"U+1F196", "NG button", "ng, NG button"},
  {"U+1F17E", "O button (blood type)", "blood type, o, O button (blood type)"},
  {"U+1F197", "OK button", "OK, OK button"},
  {"U+1F17F", "P button", "parking, P button"},
  {"U+1F198", "SOS button", "help, sos, SOS button"},
  {"U+1F199", "UP! button", "mark, up, UP! button"},
  {"U+1F19A", "VS button", "versus, vs, VS button"},
  {"U+1F201", "Japanese “here” button", "“here”, Japanese, katakana, ココ, Japanese “here” button"},
  {"U+1F202", "Japanese “service charge” button", "“service charge”, Japanese, katakana, サ, Japanese “service charge” button"},
  {"U+1F237", "Japanese “monthly amount” button", "“monthly amount”, ideograph, Japanese, 月, Japanese “monthly amount” button"},
  {"U+1F236", "Japanese “not free of charge” button", "“not free of charge”, ideograph, Japanese, 有, Japanese “not free of charge” button"},
  {"U+1F22F", "Japanese “reserved” button", "“reserved”, ideograph, Japanese, 指, Japanese “reserved” button"},
  {"U+1F250", "Japanese “bargain” button", "“bargain”, ideograph, Japanese, 得, Japanese “bargain” button"},
  {"U+1F239", "Japanese “discount” button", "“discount”, ideograph, Japanese, 割, Japanese “discount” button"},
  {"U+1F21A", "Japanese “free of charge” button", "“free of charge”, ideograph, Japanese, 無, Japanese “free of charge” button"},
  {"U+1F232", "Japanese “prohibited” button", "“prohibited”, ideograph, Japanese, 禁, Japanese “prohibited” button"},
  {"U+1F251", "Japanese “acceptable” button", "“acceptable”, ideograph, Japanese, 可, Japanese “acceptable” button"},
  {"U+1F238", "Japanese “application” button", "“application”, ideograph, Japanese, 申, Japanese “application” button"},
  {"U+1F234", "Japanese “passing grade” button", "“passing grade”, ideograph, Japanese, 合, Japanese “passing grade” button"},
  {"U+1F233", "Japanese “vacancy” button", "“vacancy”, ideograph, Japanese, 空, Japanese “vacancy” button"},
  {"U+3297", "Japanese “congratulations” button", "“congratulations”, ideograph, Japanese, 祝, Japanese “congratulations” button"},
  {"U+3299", "Japanese “secret” button", "“secret”, ideograph, Japanese, 秘, Japanese “secret” button"},
  {"U+1F23A", "Japanese “open for business” button", "“open for business”, ideograph, Japanese, 営, Japanese “open for business” button"},
  {"U+1F235", "Japanese “no vacancy” button", "“no vacancy”, ideograph, Japanese, 満, Japanese “no vacancy” button"},
  {"U+25AA", "black small square", "geometric, square, black small square"},
  {"U+25AB", "white small square", "geometric, square, white small square"},
  {"U+25FB", "white medium square", "geometric, square, white medium square"},
  {"U+25FC", "black medium square", "geometric, square, black medium square"},
  {"U+25FD", "white medium-small square", "geometric, square, white medium-small square"},
  {"U+25FE", "black medium-small square", "geometric, square, black medium-small square"},
  {"U+2B1B", "black large square", "geometric, square, black large square"},
  {"U+2B1C", "white large square", "geometric, square, white large square"},
  {"U+1F536", "large orange diamond", "diamond, geometric, orange, large orange diamond"},
  {"U+1F537", "large blue diamond", "blue, diamond, geometric, large blue diamond"},
  {"U+1F538", "small orange diamond", "diamond, geometric, orange, small orange diamond"},
  {"U+1F539", "small blue diamond", "blue, diamond, geometric, small blue diamond"},
  {"U+1F53A", "red triangle pointed up", "geometric, red, red triangle pointed up"},
  {"U+1F53B", "red triangle pointed down", "down, geometric, red, red triangle pointed down"},
  {"U+1F4A0", "diamond with a dot", "comic, diamond, geometric, inside, diamond with a dot"},
  {"U+1F518", "radio button", "button, geometric, radio, radio button"},
  {"U+1F532", "black square button", "button, geometric, square, black square button"},
  {"U+1F533", "white square button", "button, geometric, outlined, square, white square button"},
  {"U+26AA", "white circle", "circle, geometric, white circle"},
  {"U+26AB", "black circle", "circle, geometric, black circle"},
  {"U+1F534", "red circle", "circle, geometric, red, red circle"},
  {"U+1F535", "blue circle", "blue, circle, geometric, blue circle"},
  {"U+1F3C1", "chequered flag", "checkered, chequered, racing, chequered flag"},
  {"U+1F6A9", "triangular flag", "post, triangular flag"},
  {"U+1F38C", "crossed flags", "celebration, cross, crossed, Japanese, crossed flags"},
  {"U+1F3F4", "black flag", "waving, black flag"},
  {"U+1F3F3", "white flag", "waving, white flag"},
}